name: Build WebApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Nuget Restore
        run: dotnet restore --configfile NuGet.Config

      - name: Build with dotnet
        run: dotnet build -c Release --no-restore

      - name: Dotnet Test Data
        run: dotnet test -c Release --no-build

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'QROrganizer.Web/package-lock.json'

      - name: NPM Ci
        run: npm ci
        working-directory: 'QROrganizer.Web'

      - name: Set ApplicationInsightsKey
        if: github.event_name != 'pull_request'
        run: npm run setVueEnvironment -- ${{ secrets.APPLICATIONINSIGHTS_INSTRUMENTATION_KEY }}
        working-directory: 'QROrganizer.Web'

      - name: Build Vue
        run: npm run build
        working-directory: 'QROrganizer.Web'

      - name: dotnet publish
        run: dotnet publish ./QROrganizer.Web/QROrganizer.Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-restore

      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'QROrganizer'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_663904DB84234AFBA53E5933C238A11A }}
          package: .
